apiService:
  address: ":8080"
telemetryAgent:
  queueSize: 600
  maxWorkers: 1
  brokers:
    - name: ligmaNats
      type: nats
      address: "nats_main:4222"
      auth:
        method: plain
        user: test
        password: test
